### ISSUE TITLE
Who?

### ISSUE THREAD

**Issue by ooker777** [rschristian/voldephobia#2]
Call him Voldemort, Harry. Always use the proper name for things. Fear of a name increases fear of the thing itself.

**Comment by rschristian** [comment]
I heard if you say his name out loud he'll appear behind you and lecture about different back-compat strategies and the virtue of only shipping ES3

I'm sorry but I absolutely do fear that, he'll remain You-Know-Who to me

**Comment by dy** [comment]
I know another person who fits that You-Know-Who definition, with worse intentions, and also with a bunch of popular packages published.
