### ISSUE TITLE
Show top consumers of he who must not be named

### ISSUE THREAD

**Issue by benmccann** [rschristian/voldephobia#4]
I would like to be of service to the community and remove usage of packages from he who must not be named. While I've excised him (or her - but not really) from my own code bases, there are many who are still plagued by the affliction. Unfortunately, it's hard to find and help these poor souls. I would love if I could see https://www.npmjs.com/browse/depended/deep-equal sorted by monthly downloads

![Screenshot from 2024-06-21 07-53-10](https://github.com/rschristian/voldephobia/assets/322311/3c0e82c1-fd60-4fbc-86c2-85c0afbb4cfe)

**Comment by rschristian** [comment]
It's something I've briefly talked about with James for supporting [43081j/ecosystem-cleanup](https://github.com/43081j/ecosystem-cleanup) as it's indeed a bit of a struggle.

Admittedly my list of things to do is a mile long at the moment, and full of things that are actually quite pressing, so I'm not sure I'll be able to find any time to add something like this in the near future, though I think I would like to see it added.

**Comment by benmccann** [comment]
I found a list! https://packages.ecosyste.ms/registries/npmjs.org/packages/deep-equal/dependent_packages?order=desc&sort=downloads

**Comment by valadaptive** [comment]
I took a quick look and it appears that the ecosyste.ms API has a lot of false positives--most of the reverse dependencies listed in the above page don't seem to actually have `deep-equal` as a dependency.

**Comment by rschristian** [comment]
They might've done at one point though? It might be picking up on older versions

**Comment by benmccann** [comment]
yeah, I filed a couple of issues there though and the maintainer is really responsive so I think it should be addressed before too long hopefully

**Comment by valadaptive** [comment]
I created [a CLI util to round up package consumers and nested or reverse dependencies](https://github.com/valadaptive/firebreak)--it's a bit of a mess right now and eats up way more CPU than it should, but hopefully someone finds it useful.

**Comment by benmccann** [comment]
Here's the updated web UI: https://packages.ecosyste.ms/registries/npmjs.org/packages/deep-equal/dependent_packages?kind=runtime&latest=true&order=desc&sort=downloads
